package com.pkmprojects.shoppiq.exception.constants;

/**
 * Centralized constants for RFC 9457 {@link org.springframework.http.ProblemDetail}
 * custom property keys.
 *
 * <p>This class defines the string keys used to store application-specific
 * properties in Problem Detail responses. The constants ensure consistency
 * across the factory, handler, and any client code that reads these
 * properties. Using constants instead of string literals prevents typos
 * and makes refactoring safe.</p>
 *
 * <p>The properties defined here are extensions to the standard RFC 9457
 * fields. They are included in the {@code properties} map of the Problem
 * Detail object and provide additional context for error diagnosis and
 * automated handling.</p>
 *
 * @author prabhatkrmishra
 * @see com.pkmprojects.shoppiq.exception.factory.ProblemDetailFactory
 * @since 1.0.0
 */
public final class ProblemDetailProperties {

    /**
     * Property key for the timestamp indicating when the error occurred.
     *
     * <p>The value is an {@link java.time.Instant} serialized as an ISO-8601
     * string. This timestamp is generated by the Problem Detail factory using
     * the application's configured {@link java.time.Clock}.</p>
     */
    public static final String TIMESTAMP = "timestamp";

    /**
     * Property key for the stable machine-readable application error code.
     *
     * <p>The value is the {@link com.pkmprojects.shoppiq.exception.codes.ErrorCode#getCode()}
     * string (e.g., {@code "AUTH-401-002"}). Clients should use this code
     * for automated error handling rather than parsing the detail message.</p>
     */
    public static final String ERROR_CODE = "errorCode";

    /**
     * Prevents instantiation of this constants class.
     *
     * <p>The constructor throws {@link UnsupportedOperationException} to
     * enforce the static-only usage pattern. All fields are static final
     * constants and should be accessed directly on the class.</p>
     */
    private ProblemDetailProperties() {
        throw new UnsupportedOperationException("ProblemDetailProperties is a utility class and cannot be instantiated.");
    }
}
