package com.pkmprojects.shoppiq.aiservice.enums;

/**
 * Identifies the role of a message within an AI chat conversation.
 *
 * <p>This enumeration defines the four valid message roles in the AI chat
 * system. The role determines how the message is rendered in the UI
 * (e.g., different visual treatments for user vs. assistant messages)
 * and how it contributes to the AI model's conversational context
 * window.</p>
 *
 * <p>Messages are persisted with their role in the database and are used
 * for conversation history display, admin auditing, and auto-resolution
 * heuristics that examine the most recent assistant message.</p>
 *
 * @author prabhatkrmishra
 * @since 1.0.0
 */
public enum ChatMessageRole {

    /**
     * Message sent by the end user.
     *
     * <p>Represents human input in the conversation. User messages are counted
     * for the auto-resolution threshold and for the conversation summary's
     * message count display.</p>
     */
    USER,

    /**
     * Response generated by the AI assistant.
     *
     * <p>Represents the AI model's response to a user message. Assistant
     * messages are examined by the auto-resolution heuristic to determine
     * whether the assistant's last response was a closing prompt.</p>
     */
    ASSISTANT,

    /**
     * System-level message (e.g., conversation resolved, context injection).
     *
     * <p>System messages are generated by the application rather than by
     * the user or AI model. They record internal events such as
     * conversation resolution and are not included in the AI model's
     * context window.</p>
     */
    SYSTEM,

    /**
     * Output produced by a tool invocation (e.g., {@code search_products}).
     *
     * <p>Tool messages are generated when the AI model invokes a tool method
     * during conversation processing. They include the tool name for
     * attribution and are stored for admin auditing of tool usage patterns.</p>
     */
    TOOL
}
