package com.pkmprojects.shoppiq.aiservice.enums;

/**
 * Identifies the role of a message within an AI chat conversation.
 *
 * <p>
 * Each {@link com.pkmprojects.shoppiq.aiservice.entity.ChatMessage} is assigned
 * exactly one role that determines how the message should be rendered in the UI
 * and how it contributes to the conversation context.
 *
 * @author PrabhatKrMishra
 * @since 1.0.0
 */
public enum ChatMessageRole {

    /**
     * Message sent by the end user.
     */
    USER,

    /**
     * Response generated by the AI assistant.
     */
    ASSISTANT,

    /**
     * System-level message (e.g., conversation resolved, context injection).
     */
    SYSTEM,

    /**
     * Output produced by a tool invocation (e.g., {@code search_products}).
     */
    TOOL
}
