package com.pkmprojects.shoppiq.exception.formatter;

import com.pkmprojects.shoppiq.exception.codes.ErrorCode;
import org.springframework.validation.BindingResult;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;

import java.util.stream.Collectors;

/**
 * Utility responsible for formatting Bean Validation errors into
 * a human-readable message.
 *
 * <p>
 * This formatter is exclusively used for
 * {@link MethodArgumentNotValidException} generated by Jakarta Bean
 * Validation.
 * </p>
 *
 * <h2>Responsibilities</h2>
 * <ul>
 *     <li>Extract validation errors create Spring's binding result.</li>
 *     <li>Create a readable error summary.</li>
 *     <li>Keep validation formatting outside the exception handler.</li>
 * </ul>
 *
 * <h2>Example Output</h2>
 * <pre>
 * Validation failed:
 * email: must not be blank
 * password: size must be between 8 and 20
 * </pre>
 *
 * @author PrabhatKrMishra
 * @since 1.0.0
 */
public final class ValidationErrorFormatter {

    /**
     * Prevents instantiation.
     */
    private ValidationErrorFormatter() {
        throw new UnsupportedOperationException("ValidationErrorFormatter is a utility class and cannot be instantiated.");
    }

    /**
     * Formats validation errors into a readable string.
     *
     * @param bindingResult Bean Validation binding Result
     * @return formatted validation message
     */
    public static String format(BindingResult bindingResult) {

        if (!bindingResult.hasFieldErrors()) {
            return ErrorCode.VALIDATION_FAILED.getDefaultMessage();
        }

        return bindingResult.getFieldErrors().stream()
                .map(ValidationErrorFormatter::formatFieldError)
                .collect(Collectors.joining(System.lineSeparator()));
    }

    /**
     * Formats a single field validation error.
     *
     * @param fieldError validation field error
     * @return formatted field error
     */
    private static String formatFieldError(FieldError fieldError) {
        return "%s: %s".formatted(fieldError.getField(), fieldError.getDefaultMessage());
    }
}