package com.pkmprojects.shoppiq.exception.business;

import com.pkmprojects.shoppiq.exception.base.ShoppiqException;
import com.pkmprojects.shoppiq.exception.codes.ErrorCode;
import org.springframework.http.HttpStatus;

/**
 * Thrown when the application fails to generate a unique slug after exhausting retries.
 *
 * <p>This exception is thrown by the slug generation utility when it
 * cannot produce a unique URL slug after the maximum number of retry
 * attempts. Slugs are generated by converting an entity name to a
 * URL-safe string and appending a numeric suffix if a collision is
 * detected. This exception indicates that the slug namespace for the
 * given entity type is nearly full.</p>
 *
 * <p>This is an extremely rare error that typically indicates a data
 * quality issue (e.g., thousands of entities with similar names). The
 * exception uses HTTP 500 Internal Server Error status because the
 * failure is on the server side. The detail message includes the entity
 * type, the name that failed, and the number of attempts made.</p>
 *
 * @author prabhatkrmishra
 * @see ErrorCode#SLUG_GENERATION_FAILED
 * @since 1.0.0
 */
public final class SlugGenerationFailedException extends ShoppiqException {

    private SlugGenerationFailedException(String detail) {
        super(ErrorCode.SLUG_GENERATION_FAILED, HttpStatus.INTERNAL_SERVER_ERROR, detail);
    }

    /**
     * Creates an exception indicating that slug generation failed for
     * the given entity after the maximum number of attempts.
     *
     * @param entityType  the entity type (e.g. "item", "category", "store")
     * @param name        the name used to generate the slug
     * @param maxAttempts the maximum retry attempts exhausted
     * @return slug generation failed exception
     */
    public static SlugGenerationFailedException forEntity(String entityType, String name, int maxAttempts) {
        return new SlugGenerationFailedException(
                "Failed to generate unique slug after %d attempts for %s: %s"
                        .formatted(maxAttempts, entityType, name)
        );
    }
}
