package com.pkmprojects.shoppiq.dto.admin.report;

import java.math.BigDecimal;

/**
 * Aggregated sales performance data for a single product category.
 *
 * <p>This record is used in admin reports to provide a per-category
 * breakdown of sales metrics including total quantity sold, total
 * revenue, and the number of distinct products that contributed to
 * those figures. It helps administrators understand which categories
 * are performing well and which may need promotional attention.</p>
 *
 * <p>This is a read-only projection DTO designed for JPQL constructor
 * expressions. It carries no validation constraints and is never used
 * as a request body. Instances are produced by the reporting repository
 * and consumed by the admin report response assembly logic.</p>
 *
 * @param categoryId         unique identifier of the category,
 *                           corresponding to the {@code Category} entity's primary key
 * @param categoryName       human-readable display name of the category
 * @param quantitySold       total number of individual product units sold
 *                           within this category across all qualifying orders
 * @param revenue            aggregate monetary revenue generated by all products
 *                           in this category, in the platform's base currency
 * @param uniqueProductsSold count of distinct products that contributed
 *                           sales within this category; useful for
 *                           understanding category breadth versus depth
 * @author prabhatkrmishra
 * @since 1.0.0
 */
public record CategoryPerformanceData(
        /**
         * Unique identifier of the category.
         */
        Long categoryId,
        /**
         * Display name of the category.
         */
        String categoryName,
        /**
         * Total number of units sold in this category.
         */
        long quantitySold,
        /**
         * Total revenue generated from this category.
         */
        BigDecimal revenue,
        /**
         * Number of distinct products sold within the category.
         */
        long uniqueProductsSold
) {
}
