package com.pkmprojects.shoppiq.dto.admin.report;

import java.math.BigDecimal;

/**
 * <strong>Spring Boot Concept:</strong> Data transfer record for individual product sales performance.
 *
 * <p>Provides aggregated sales metrics for a single product, including
 * total quantity sold, revenue generated, average selling price, and
 * current inventory level.</p>
 *
 * <p><b>Design note:</b> Like the other report DTOs, this Java record is a
 * <i>read-only projection</i> used in the admin reporting module. Records
 * are ideal here because they are immutable (data cannot be accidentally
 * modified after creation) and the compact syntax makes the data shape
 * immediately visible.</p>
 *
 * @param itemId       the unique identifier of the product
 * @param itemName     the display name of the product
 * @param sku          the stock-keeping unit identifier
 * @param quantitySold total number of units sold
 * @param revenue      total revenue generated by this product
 * @param averagePrice the average selling price across all sales
 * @param currentStock the current inventory level
 * @author prabhatkrmishra
 * @since 1.0.0
 */
public record ProductPerformanceData(Long itemId, String itemName, String sku, long quantitySold,
                                     BigDecimal revenue, BigDecimal averagePrice, int currentStock) {
}
