package com.pkmprojects.shoppiq.dto.admin.report;

import java.math.BigDecimal;

/**
 * Individual product sales performance data for admin reports.
 *
 * <p>This record provides per-product aggregated sales metrics including
 * total quantity sold, revenue, average selling price, and current
 * inventory level. It is used in product performance reports to help
 * administrators identify top sellers, slow-moving inventory, and
 * pricing optimization opportunities across the product catalog.</p>
 *
 * <p>This is a read-only projection DTO designed for JPQL constructor
 * expressions. It carries no validation constraints and is never used
 * as a request body. Instances are produced by the reporting repository
 * and consumed by the admin report response assembly logic.</p>
 *
 * @param itemId       unique identifier of the product, corresponding to
 *                     the {@code Item} entity's primary key
 * @param itemName     human-readable product name as displayed in the
 *                     storefront and admin panel
 * @param sku          Stock Keeping Unit identifier for warehouse and
 *                     inventory tracking
 * @param quantitySold total number of individual units of this product
 *                     sold across all qualifying orders
 * @param revenue      aggregate monetary revenue generated by this product,
 *                     in the platform's base currency
 * @param averagePrice average selling price per unit across all sales,
 *                     useful for pricing analysis and discount impact
 *                     assessment
 * @param currentStock current inventory level for this product;
 *                     helps identify restocking needs alongside
 *                     sales velocity
 * @author prabhatkrmishra
 * @since 1.0.0
 */
public record ProductPerformanceData(
        /**
         * Unique identifier of the product.
         */
        Long itemId,
        /**
         * Display name of the product.
         */
        String itemName,
        /**
         * Stock Keeping Unit identifier.
         */
        String sku,
        /**
         * Total number of units sold.
         */
        long quantitySold,
        /**
         * Total revenue generated by this product.
         */
        BigDecimal revenue,
        /**
         * Average selling price across all sales.
         */
        BigDecimal averagePrice,
        /**
         * Current inventory level.
         */
        int currentStock
) {
}
