package com.pkmprojects.shoppiq.entity.seller;

import com.pkmprojects.shoppiq.audit.AuditableEntity;
import com.pkmprojects.shoppiq.enums.StoreStatus;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

/**
 * Represents a seller's store on the Shoppiq marketplace.
 *
 * <p>Each seller has exactly one store, created automatically in
 * {@code DRAFT} status when the seller is approved by an administrator.
 * The seller must complete the store profile (name, description, logo,
 * banner) before publishing. The unique {@code slug} enables
 * SEO-friendly URL routing for the storefront (e.g.
 * {@code /store/acme-electronics}).</p>
 *
 * <p>The store's publishing status ({@link StoreStatus}) controls whether
 * the storefront is visible to customers. Stores in {@code DRAFT} status
 * are only visible to the owning seller and administrators. Published
 * stores appear in seller directories and are linked from product
 * listings.</p>
 *
 * @author prabhatkrmishra
 * @see Seller
 * @see StoreStatus
 * @since 1.0.0
 */
@Entity
@Table(name = "stores")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class Store extends AuditableEntity {

    /**
     * The seller who owns this store.
     *
     * <p>One-to-one relationship: each seller has exactly one store. The
     * {@code seller_id} column carries a unique constraint to enforce
     * this invariant at the database level. The seller reference is
     * lazily loaded to avoid unnecessary joins when accessing store
     * details independently.</p>
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(
            name = "seller_id",
            nullable = false,
            unique = true,
            foreignKey = @ForeignKey(name = "fk_stores_seller")
    )
    private Seller seller;

    /**
     * Display name of the store shown on product listings, the seller
     * storefront, and in search results.
     *
     * <p>Required field with a maximum length of 255 characters. This is
     * the primary public-facing identifier for the seller's brand and
     * appears throughout the customer experience. Must be provided before
     * the store can be published.</p>
     */
    @NotBlank
    @Column(name = "store_name", nullable = false, length = 255)
    private String storeName;

    /**
     * URL-friendly unique identifier for the store, used for SEO-optimized
     * storefront routing.
     *
     * <p>Required field with a maximum length of 100 characters. Must be
     * globally unique across all stores. The slug appears in URLs such as
     * {@code /store/acme-electronics}. Generated by the service layer to
     * ensure consistency and collision-free naming.</p>
     */
    @NotBlank
    @Column(nullable = false, unique = true, length = 100)
    private String slug;

    /**
     * Store description explaining the seller's product range, specialty,
     * and value proposition to customers.
     *
     * <p>Stored as a TEXT column to accommodate lengthy descriptions.
     * Displayed on the storefront homepage to help customers understand
     * the seller's offerings. May include information about product
     * categories, shipping policies, and customer service commitments.</p>
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * URL or storage key pointing to the store's logo image asset.
     *
     * <p>Optional field with a maximum length of 500 characters. Displayed
     * on the storefront header, product listings, and in search results
     * to establish brand identity. May be {@code null} if the seller has
     * not yet uploaded a logo.</p>
     */
    @Column(length = 500)
    private String logo;

    /**
     * URL or storage key pointing to the store's banner image asset.
     *
     * <p>Optional field with a maximum length of 500 characters. Displayed
     * as a hero image on the storefront homepage to establish visual
     * branding. May be {@code null} if the seller has not yet uploaded
     * a banner image.</p>
     */
    @Column(length = 500)
    private String banner;

    /**
     * Publishing status controlling the store's visibility in the
     * marketplace and search results.
     *
     * <p>Stored as a string enum with a maximum length of 20 characters.
     * New stores start as {@code DRAFT} and must be published by the
     * seller after completing the profile. Published stores are visible
     * to customers in seller directories and product listings. Stores
     * can be suspended or deactivated by administrators.</p>
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private StoreStatus status;
}
