package com.pkmprojects.shoppiq.dto.admin.analytics;

import java.math.BigDecimal;

/**
 * Top-performing product category data point for the admin analytics dashboard.
 *
 * <p>This record represents a single product category ranked by its total
 * revenue contribution. It is used to render the "Top Categories" widget
 * on the administrator dashboard, helping administrators identify which
 * product segments are driving the most sales. Each instance includes
 * the category's identifier, display name, aggregate quantity sold, and
 * total revenue for the selected time period.</p>
 *
 * <p>This is a read-only analytics projection designed for JPQL
 * constructor expressions. It carries no validation constraints and
 * is never used as a request body. Instances are produced exclusively
 * by the data access layer.</p>
 *
 * @param categoryId        unique identifier of the product category,
 *                          corresponding to the {@code Category} entity's primary key
 * @param categoryName      human-readable display name of the category as
 *                          shown in the storefront navigation
 * @param totalQuantitySold aggregate number of individual product units
 *                          sold within this category during the reporting period
 * @param totalRevenue      aggregate monetary revenue generated by all products
 *                          in this category, in the platform's base currency
 * @author prabhatkrmishra
 * @since 1.0.0
 */
public record TopCategoryData(
        /**
         * Unique identifier of the category.
         */
        Long categoryId,

        /**
         * Display name of the category.
         */
        String categoryName,

        /**
         * Total number of units sold in this category.
         */
        Long totalQuantitySold,

        /**
         * Total revenue generated from this category.
         */
        BigDecimal totalRevenue
) {
}
