package com.pkmprojects.shoppiq.dto.admin.analytics;

import java.math.BigDecimal;

/**
 * Top-selling product data point for the admin analytics dashboard.
 *
 * <p>This record represents a single product ranked by its total revenue
 * contribution within a given reporting period. It powers the "Top
 * Selling Products" widget on the administrator dashboard, enabling
 * administrators to quickly identify best-sellers and inventory
 * planning candidates. Each instance includes the product's identifier,
 * display name, SKU, aggregate quantity sold, and total revenue.</p>
 *
 * <p>This is a read-only analytics projection designed for JPQL
 * constructor expressions. It carries no validation constraints and
 * is never used as a request body. Instances are produced exclusively
 * by the data access layer.</p>
 *
 * @param itemId            unique identifier of the product (the {@code Item}
 *                          entity's primary key)
 * @param itemName          human-readable product name as displayed in the
 *                          storefront and admin panel
 * @param sku               Stock Keeping Unit identifier for warehouse and
 *                          inventory tracking purposes
 * @param totalQuantitySold aggregate number of individual units of
 *                          this product sold during the reporting period
 * @param totalRevenue      aggregate monetary revenue generated by this
 *                          product across all qualifying orders, in the
 *                          platform's base currency
 * @author prabhatkrmishra
 * @since 1.0.0
 */
public record TopSellingProductData(
        /**
         * Unique identifier of the product.
         */
        Long itemId,

        /**
         * Display name of the product.
         */
        String itemName,

        /**
         * Stock Keeping Unit identifier.
         */
        String sku,

        /**
         * Total number of units sold.
         */
        Long totalQuantitySold,

        /**
         * Total revenue generated by this product.
         */
        BigDecimal totalRevenue
) {
}
