package com.pkmprojects.shoppiq.dto.banner;

import com.pkmprojects.shoppiq.entity.banner.Banner;
import com.pkmprojects.shoppiq.entity.enums.BannerType;

import java.time.Instant;

/**
 * Response DTO for homepage banner detail data.
 *
 * <p>This record is the read-only counterpart of {@link BannerRequest}.
 * It includes all request fields plus server-managed metadata ({@code id},
 * {@code createdAt}, {@code updatedAt}) that are not present in the
 * request. It is returned by the banner list and detail endpoints for
 * both the admin management UI and the storefront banner rendering.</p>
 *
 * <p>The static {@link #from(Banner)} factory method converts the JPA
 * entity to this DTO, providing a centralized entity-to-DTO mapping
 * that decouples the API contract from the persistence layer. This
 * pattern ensures that changes to the entity schema do not propagate
 * to API consumers.</p>
 *
 * @param id           unique identifier of the banner, auto-generated by the database
 * @param badgeText    badge pill label text (e.g. "Limited Time")
 * @param badgeType    visual style variant for the badge pill
 *                     (PRIMARY, SECONDARY, ACCENT)
 * @param heading      main heading text of the banner
 * @param bodyText     optional description text; may be null
 * @param buttonText   optional CTA button label; may be null
 * @param buttonLink   optional CTA button URL; may be null
 * @param headingColor hex color for the heading text (e.g. #FFFFFF)
 * @param bodyColor    color for the body text (hex or rgba format)
 * @param displayOrder sort order on the homepage; lower values appear first
 * @param active       whether this banner is currently displayed on the homepage
 * @param createdAt    timestamp when the banner was first created
 * @param updatedAt    timestamp of the most recent modification to the banner
 * @author prabhatkrmishra
 * @since 1.0.0
 */
public record BannerResponse(

        /**
         * Unique identifier of the banner.
         */
        Long id,

        /**
         * Badge pill label (e.g., "Limited Time").
         */
        String badgeText,

        /**
         * Visual style variant (PRIMARY, SECONDARY, ACCENT).
         */
        BannerType badgeType,

        /**
         * Main heading text.
         */
        String heading,

        /**
         * Optional description text.
         */
        String bodyText,

        /**
         * Optional CTA button label.
         */
        String buttonText,

        /**
         * Optional CTA button URL.
         */
        String buttonLink,

        /**
         * Hex color for heading (e.g., #FFFFFF).
         */
        String headingColor,

        /**
         * Color for body text (hex or rgba).
         */
        String bodyColor,

        /**
         * Sort order on homepage (lower = earlier).
         */
        Integer displayOrder,

        /**
         * Whether to display on homepage.
         */
        Boolean active,

        /**
         * Entity creation timestamp.
         */
        Instant createdAt,

        /**
         * Entity last update timestamp.
         */
        Instant updatedAt
) {

    /**
     * Constructs a {@link BannerResponse} from a {@link Banner} entity.
     *
     * @param banner source entity
     * @return response DTO
     */
    public static BannerResponse from(Banner banner) {
        return new BannerResponse(
                banner.getId(),
                banner.getBadgeText(),
                banner.getBadgeType(),
                banner.getHeading(),
                banner.getBodyText(),
                banner.getButtonText(),
                banner.getButtonLink(),
                banner.getHeadingColor(),
                banner.getBodyColor(),
                banner.getDisplayOrder(),
                banner.isActive(),
                banner.getCreatedAt(),
                banner.getUpdatedAt()
        );
    }
}
