package com.pkmprojects.shoppiq.dto.item;

import com.pkmprojects.shoppiq.dto.category.CategoryResponse;
import com.pkmprojects.shoppiq.entity.item.Item;
import com.pkmprojects.shoppiq.enums.ProductPublishingStatus;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Response DTO returned for product resources in the catalog API.
 *
 * <p>This record represents the complete product information exposed by
 * the catalog REST API, combining general product information from the
 * {@code Item} entity with commercial details from the {@code ItemDetails}
 * entity. It is returned by the product list and detail endpoints and
 * serves as the primary data structure for storefront product display.</p>
 *
 * <p>The DTO uses a nested {@link CategoryResponse} instead of exposing
 * the Category entity directly, preventing circular references and
 * lazy-loading issues while demonstrating clean DTO composition. The
 * static {@link #fromEntity(Item)} factory method traverses the
 * {@code Item → ItemDetails → Category} entity graph to flatten the
 * data into a single immutable record.</p>
 *
 * @param publishingStatus   current publishing lifecycle status
 *                           (DRAFT, PUBLISHED, REJECTED) controlling
 *                           storefront visibility
 * @param id                 unique product identifier, auto-generated by the database
 * @param itemDetailsId      identifier of the {@code ItemDetails} record,
 *                           needed for cart and order operations that
 *                           reference the specific variant
 * @param name               product display name as shown in the storefront
 * @param slug               URL-friendly identifier derived from the product name;
 *                           used in product detail page URLs
 * @param description        product description text for the detail page
 * @param brand              product manufacturer or brand name
 * @param sku                Stock Keeping Unit identifier for inventory tracking
 * @param price              current selling price of the product
 * @param stockQuantity      current available inventory count
 * @param discountPercentage discount percentage applied to the base price
 * @param imageUrl           URL of the product's primary image
 * @param category           nested category response providing category context
 * @param createdAt          timestamp when the product was first created
 * @param updatedAt          timestamp of the most recent product modification
 * @author prabhatkrmishra
 * @since 1.0.0
 */
public record ItemResponse(

        /**
         * Publishing status of the product.
         */
        ProductPublishingStatus publishingStatus,

        /**
         * Unique product identifier.
         */
        Long id,

        /**
         * ItemDetails identifier — needed for cart operations.
         */
        Long itemDetailsId,

        /**
         * Product name.
         */
        String name,

        /**
         * URL-friendly slug derived from product name.
         */
        String slug,

        /**
         * Product description.
         */
        String description,

        /**
         * Product manufacturer.
         */
        String brand,

        /**
         * Stock Keeping Unit.
         */
        String sku,

        /**
         * Current selling price.
         */
        BigDecimal price,

        /**
         * Current inventory.
         */
        Integer stockQuantity,

        /**
         * Product discount percentage.
         */
        BigDecimal discountPercentage,

        /**
         * Product image URL.
         */
        String imageUrl,

        /**
         * Product category.
         */
        CategoryResponse category,

        /**
         * Creation timestamp.
         */
        Instant createdAt,

        /**
         * Last modification timestamp.
         */
        Instant updatedAt

) {

    /**
     * Creates an {@code ItemResponse} from an {@link Item} entity.
     *
     * <p>
     * This factory method centralizes the mapping logic between the
     * persistence layer and the API layer.
     * </p>
     *
     * @param item item entity
     * @return mapped response DTO
     */
    public static ItemResponse fromEntity(Item item) {
        return new ItemResponse(
                item.getPublishingStatus(),
                item.getId(),
                item.getItemDetails().getId(),
                item.getName(),
                item.getSlug(),
                item.getDescription(),
                item.getItemDetails().getBrand(),
                item.getItemDetails().getSku(),
                item.getItemDetails().getPrice(),
                item.getItemDetails().getStockQuantity(),
                item.getItemDetails().getDiscountPercentage(),
                item.getItemDetails().getImageUrl(),

                CategoryResponse.fromEntity(
                        item.getItemDetails().getCategory()
                ),

                item.getCreatedAt(),
                item.getUpdatedAt()
        );
    }
}
