package com.pkmprojects.shoppiq.entity.category;

import com.pkmprojects.shoppiq.audit.AuditableEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.*;

/**
 * Represents a product category within the Shoppiq catalog.
 *
 * <p>Classifies products into logical groups such as "Electronics",
 * "Fashion", and "Home Appliances". Each category has a human-readable
 * name and a URL-friendly slug used for SEO-optimized routing. Slug
 * generation is delegated to the service layer to ensure consistency
 * and uniqueness across the catalog.</p>
 *
 * <p>Categories serve as the primary taxonomy for product discovery and
 * navigation. Every product must belong to exactly one category, and the
 * category relationship is normalized via a foreign key rather than stored
 * as raw text. Both the {@code name} and {@code slug} fields carry unique
 * database constraints to prevent duplicates.</p>
 *
 * @author prabhatkrmishra
 * @see com.pkmprojects.shoppiq.entity.item.ItemDetails
 * @since 1.0.0
 */
@Entity
@Table(
        name = "categories",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_categories_name", columnNames = "name"),
                @UniqueConstraint(name = "uk_categories_slug", columnNames = "slug")
        }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class Category extends AuditableEntity {

    /**
     * Human-readable category name displayed in navigation menus,
     * product listings, and breadcrumb trails.
     *
     * <p>Required field with a maximum length of 100 characters. Must
     * be unique across all categories in the system. The name is the
     * primary label shown to customers when browsing or filtering
     * products by category.</p>
     */
    @NotBlank
    @Size(max = 100)
    @Column(nullable = false, length = 100)
    private String name;

    /**
     * URL-friendly identifier derived from the category name, used for
     * SEO-optimized routing in the storefront.
     *
     * <p>Required field with a maximum length of 120 characters. Must
     * be unique across all categories. Typically generated by
     * lowercasing the name, replacing spaces with hyphens, and removing
     * special characters. The slug appears in URLs such as
     * {@code /category/electronics}.</p>
     */
    @NotBlank
    @Size(max = 120)
    @Column(nullable = false, length = 120)
    private String slug;

    /**
     * Optional descriptive text explaining what products this category
     * contains, its scope, and any inclusion/exclusion criteria.
     *
     * <p>Maximum length of 255 characters. When present, displayed on
     * the category listing page to help customers understand what to
     * expect. May be {@code null} for categories where the name alone
     * is sufficiently descriptive.</p>
     */
    @Size(max = 255)
    @Column(length = 255)
    private String description;

}
