package com.pkmprojects.shoppiq.dto.category;

import com.pkmprojects.shoppiq.entity.category.Category;

import java.util.Objects;

/**
 * Response DTO for category data returned to API consumers.
 *
 * <p>This record contains all publicly visible category information
 * including the auto-generated slug for URL-friendly access. It is
 * returned by the category endpoints ({@code GET /api/category},
 * {@code GET /api/category/{id}},
 * {@code GET /api/category/by-slug/{slug}}) and is used in the
 * storefront navigation and category landing pages.</p>
 *
 * <p>The static {@link #fromEntity(Category)} factory method provides
 * a centralized entity-to-DTO mapping that keeps the JPA entity
 * layer internal. Java records are ideal for response DTOs because
 * they are inherently immutable, preventing accidental modification
 * of API response data after construction.</p>
 *
 * @param id          unique identifier of the category, auto-generated by the database
 * @param name        human-readable category name as displayed in the storefront
 * @param slug        URL-friendly identifier derived from the name; used in
 *                    REST endpoints for clean, SEO-friendly URLs
 *                    (e.g. /api/category/by-slug/electronics-gadgets)
 * @param description optional long-form description displayed on the
 *                    category landing page; may be null
 * @author prabhatkrmishra
 * @since 1.0.0
 */
public record CategoryResponse(

        /**
         * Unique identifier of the category.
         * Generated by the database.
         */
        Long id,

        /**
         * Human-readable category name.
         * Same as in the request, preserved for display purposes.
         */
        String name,

        /**
         * URL-friendly slug derived from the name.
         * Used in REST endpoints for clean, SEO-friendly URLs.
         *
         * <p>Example: /api/category/by-slug/electronics-gadgets</p>
         *
         * @see com.pkmprojects.shoppiq.util.SlugUtil#generate(String)
         */
        String slug,

        /**
         * Optional description of the category.
         * Nullable; may not be present in the response.
         */
        String description

) {
    /**
     * Factory method to create a CategoryResponse from a Category entity.
     *
     * <p>Convenience method that centralizes the mapping logic,
     * making it easy to convert between entity and DTO layers.</p>
     *
     * @param category the category entity to convert
     * @return a new CategoryResponse instance with values extracted from the entity
     */
    public static CategoryResponse fromEntity(Category category) {

        Objects.requireNonNull(category, "Category cannot be null.");

        return new CategoryResponse(
                category.getId(),
                category.getName(),
                category.getSlug(),
                category.getDescription()
        );
    }
}
