package com.pkmprojects.shoppiq.aiservice.service;

import dev.langchain4j.service.MemoryId;
import dev.langchain4j.service.UserMessage;
import reactor.core.publisher.Flux;

/**
 * LangChain4j service interface for streaming (token-by-token) chat.
 *
 * <p>This package-private interface is used by LangChain4j's AiServices
 * builder to create dynamic proxies that handle streaming AI chat
 * requests. The proxy returns a {@link Flux} of response tokens for
 * real-time rendering in the UI via Server-Sent Events.</p>
 *
 * <p>Like the synchronous variant, the streaming proxy manages chat
 * memory, system message injection, tool execution, and RAG content
 * retrieval, but delivers the response incrementally as tokens are
 * generated by the model.</p>
 *
 * @author prabhatkrmishra
 * @see ShoppiqAssistant
 * @since 1.0.0
 */
interface ShoppiqStreamingAssistant {

    /**
     * Sends a user message and returns the AI response as a reactive token stream.
     *
     * <p>The LangChain4j proxy intercepts this call and performs the full
     * AI pipeline, returning each generated token as it becomes available
     * via the {@link Flux}. This enables real-time token-by-token rendering
     * in the frontend chat interface.</p>
     *
     * @param message the user's message text
     * @param chatId  the conversation identifier used as the memory ID
     * @return a {@link Flux} of response tokens
     */
    Flux<String> chat(@UserMessage String message, @MemoryId String chatId);
}
