package com.pkmprojects.shoppiq.dto.admin.response;

import com.pkmprojects.shoppiq.dto.address.AddressResponse;
import com.pkmprojects.shoppiq.entity.address.Address;
import com.pkmprojects.shoppiq.entity.order.Order;
import com.pkmprojects.shoppiq.entity.order.OrderAddressSnapshot;
import com.pkmprojects.shoppiq.enums.OrderStatus;
import com.pkmprojects.shoppiq.enums.PaymentMethod;
import com.pkmprojects.shoppiq.enums.PaymentStatus;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

/**
 * Comprehensive response DTO for admin order management.
 *
 * <p>This record provides a full view of an order for administrators,
 * including customer identification, shipping address, payment status,
 * financial breakdown, and all order line items. It is returned by the
 * admin order list and detail endpoints and is designed for the admin
 * order management UI where administrators need to review, manage,
 * and fulfill customer orders.</p>
 *
 * <p>The address field uses the address snapshot pattern: the shipping
 * address is captured at checkout time and stored as an immutable
 * snapshot, preserving historical accuracy even if the customer
 * later modifies their saved address. The static
 * {@link #fromEntity(Order)} factory method handles the
 * snapshot-to-DTO conversion with fallback to the live address for
 * legacy orders that predate the snapshot feature.</p>
 *
 * @param id               unique identifier of the order, auto-generated by the database
 * @param customerUsername username of the customer who placed the order
 * @param customerEmail    email address of the customer for admin follow-up
 * @param address          shipping address snapshot (or live fallback for legacy orders)
 * @param status           current order status in the fulfillment lifecycle
 *                         (PLACED, CONFIRMED, SHIPPED, DELIVERED, CANCELLED)
 * @param paymentMethod    payment method used at checkout (CREDIT_CARD, UPI, COD)
 * @param paymentStatus    current payment status (PENDING, PAID, FAILED, REFUNDED)
 * @param subtotal         sum of all line item totals before fees or discounts
 * @param deliveryCharge   shipping fee based on the selected delivery type
 * @param codSurcharge     additional surcharge applied for cash-on-delivery orders
 * @param tax              applicable tax amount computed at checkout time
 * @param discount         promo code discount amount applied to the order
 * @param grandTotal       final amount the customer pays, inclusive of all fees
 * @param placedAt         timestamp when the order was successfully placed
 * @param items            list of order line items with product snapshots and quantities
 * @author prabhatkrmishra
 * @since 1.0.0
 */
public record AdminOrderResponse(

        /**
         * Order identifier.
         */
        Long id,

        /**
         * Customer username.
         */
        String customerUsername,

        /**
         * Customer email.
         */
        String customerEmail,

        /**
         * Shipping address.
         */
        AddressResponse address,

        /**
         * Current order status.
         */
        OrderStatus status,

        /**
         * Payment method used.
         */
        PaymentMethod paymentMethod,

        /**
         * Current payment status.
         */
        PaymentStatus paymentStatus,

        /**
         * Order subtotal.
         */
        BigDecimal subtotal,

        /**
         * Delivery charge based on delivery type.
         */
        BigDecimal deliveryCharge,

        /**
         * Cash-on-delivery surcharge.
         */
        BigDecimal codSurcharge,

        /**
         * Tax amount.
         */
        BigDecimal tax,

        /**
         * Discount applied.
         */
        BigDecimal discount,

        /**
         * Grand total payable.
         */
        BigDecimal grandTotal,

        /**
         * Order placement timestamp.
         */
        Instant placedAt,

        /**
         * Order line items.
         */
        List<OrderItemResponse> items
) {

    /**
     * Creates an {@code AdminOrderResponse} from an {@link Order} entity.
     *
     * @param order order entity
     * @return mapped response DTO
     */
    public static AdminOrderResponse fromEntity(Order order) {
        AddressResponse addressResponse = toAddressResponse(
                order.getShippingAddress(), order.getAddress());

        List<OrderItemResponse> itemResponses = order.getOrderItems().stream()
                .map(item -> new OrderItemResponse(
                        item.getId(),
                        item.getItemNameSnapshot(),
                        item.getUnitPriceSnapshot(),
                        item.getQuantity(),
                        item.getSubtotal()
                ))
                .toList();

        return new AdminOrderResponse(
                order.getId(),
                order.getUser().getUsername(),
                order.getUser().getEmail(),
                addressResponse,
                order.getStatus(),
                order.getPaymentMethod(),
                order.getPaymentStatus(),
                order.getSubtotal(),
                order.getDeliveryCharge(),
                order.getCodSurcharge(),
                order.getTax(),
                order.getDiscount(),
                order.getGrandTotal(),
                order.getPlacedAt(),
                itemResponses
        );
    }

    /**
     * Builds an {@link AddressResponse} from the snapshot, falling back to
     * the live address entity for legacy orders that predate the snapshot.
     */
    private static AddressResponse toAddressResponse(OrderAddressSnapshot snapshot,
                                                     Address liveAddress) {
        if (snapshot != null) {
            return new AddressResponse(
                    null,                               // id — not present in snapshot
                    null,                               // label — not relevant in order context
                    snapshot.getFullName(),
                    snapshot.getPhone(),
                    snapshot.getLine1(),
                    snapshot.getLine2(),
                    snapshot.getCity(),
                    snapshot.getState(),
                    snapshot.getPostalCode(),
                    snapshot.getCountry(),
                    false,                              // isDefault — not snapshot data
                    null,                               // createdAt — not snapshot data
                    null                                // updatedAt — not snapshot data
            );
        }
        if (liveAddress != null) {
            return AddressResponse.from(liveAddress);
        }
        return null;
    }

    /**
     * Order line item data for the admin order detail view.
     *
     * <p>Contains the product name and unit price snapshots captured at
     * the time of purchase, preserving historical accuracy. The subtotal
     * is computed as {@code unitPriceSnapshot * quantity}.</p>
     *
     * @param id                unique identifier of the order item record
     * @param itemNameSnapshot  product name at the time of purchase
     * @param unitPriceSnapshot unit price at the time of purchase
     * @param quantity          number of units ordered for this line item
     * @param subtotal          line total computed as {@code unitPriceSnapshot * quantity}
     */
    public record OrderItemResponse(

            /**
             * Order item identifier.
             */
            Long id,

            /**
             * Product name snapshot at purchase.
             */
            String itemNameSnapshot,

            /**
             * Unit price snapshot at purchase.
             */
            BigDecimal unitPriceSnapshot,

            /**
             * Quantity ordered.
             */
            int quantity,

            /**
             * Line subtotal (unit price × quantity).
             */
            BigDecimal subtotal
    ) {
    }
}
