package com.pkmprojects.shoppiq.dto.admin.response;

import java.math.BigDecimal;

/**
 * Admin-facing commission report DTO for seller financial analysis.
 *
 * <p>This record provides per-seller commission details including total
 * order volume, revenue contribution, the seller's commission rate, and
 * the computed commission amount earned by the platform. It is returned
 * by the admin commission report endpoint and is designed for financial
 * reporting and seller payout reconciliation.</p>
 *
 * <p>The {@code commissionEarned} value is computed server-side as
 * {@code totalRevenue * commissionRate / 100} using the static
 * {@link #from} factory method, ensuring that the displayed commission
 * is always consistent with the underlying data. The commission rate
 * is stored as a percentage (e.g. 10.00 represents 10%).</p>
 *
 * @param sellerId         unique identifier of the seller entity
 * @param businessName     registered business name of the seller for display
 * @param totalOrders      total number of orders containing this seller's products
 *                         across all order statuses
 * @param totalRevenue     aggregate monetary revenue generated by this seller's
 *                         products in confirmed/paid orders, in the platform's
 *                         base currency
 * @param commissionRate   the seller's commission rate as a percentage
 *                         (e.g. 10.00 means 10%); set during seller onboarding
 * @param commissionEarned computed commission amount that the platform earns
 *                         from this seller's sales; calculated as
 *                         {@code totalRevenue * commissionRate / 100}
 * @author prabhatkrmishra
 * @since 1.0.0
 */
public record CommissionReportResponse(
        /**
         * Seller identifier.
         */
        Long sellerId,

        /**
         * Seller business name.
         */
        String businessName,

        /**
         * Total orders containing seller's products.
         */
        long totalOrders,

        /**
         * Total revenue from seller's items in paid orders.
         */
        BigDecimal totalRevenue,

        /**
         * Seller's commission rate (percentage).
         */
        BigDecimal commissionRate,

        /**
         * Computed commission amount.
         */
        BigDecimal commissionEarned
) {
    /**
     * Creates a commission report response with computed commission amount.
     *
     * @param sellerId       seller identifier
     * @param businessName   seller business name
     * @param totalOrders    total orders containing seller's products
     * @param totalRevenue   total revenue from seller's items
     * @param commissionRate seller's commission rate (percentage)
     * @return populated response DTO with computed commissionEarned
     */
    public static CommissionReportResponse from(
            Long sellerId,
            String businessName,
            long totalOrders,
            BigDecimal totalRevenue,
            BigDecimal commissionRate
    ) {
        BigDecimal commissionEarned = totalRevenue.multiply(
                commissionRate.divide(BigDecimal.valueOf(100), 4, java.math.RoundingMode.HALF_UP)
        ).setScale(2, java.math.RoundingMode.HALF_UP);

        return new CommissionReportResponse(
                sellerId, businessName, totalOrders, totalRevenue,
                commissionRate, commissionEarned
        );
    }
}
