package com.pkmprojects.shoppiq.dto.address;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.pkmprojects.shoppiq.entity.address.Address;

import java.time.Instant;

/**
 * Response payload representing a single saved shipping or billing address
 * belonging to an authenticated user.
 *
 * <p>This DTO is returned by the address management endpoints
 * ({@code GET /api/addresses}, {@code GET /api/addresses/{id}}) whenever
 * the client needs to display, select, or confirm an address. It provides
 * a human-readable label (e.g. "Home", "Office"), full recipient
 * details, and timestamp metadata so the frontend can render address
 * cards and show when the address was last modified.</p>
 *
 * <p>This is a response-only DTO with no incoming validation constraints.
 * It uses {@link com.fasterxml.jackson.annotation.JsonProperty @JsonProperty("default")}
 * on the {@code isDefault} field to serialize the boolean as
 * {@code "default"} in JSON, avoiding a reserved-word conflict.
 * The record is constructed via the static {@link #from(Address)}
 * factory method which maps directly from the JPA entity.</p>
 *
 * @param id         unique identifier of the address, auto-generated by the database
 * @param label      user-defined label for quick identification (e.g. "Home", "Office"),
 *                   typically limited to 30 characters
 * @param fullName   full name of the recipient at this address
 * @param phone      contact phone number for delivery coordination
 * @param line1      primary street address line (required for all addresses)
 * @param line2      secondary address line for apartment, suite, or floor details
 * @param city       city or municipality name
 * @param state      state, province, or region name
 * @param postalCode postal code, ZIP code, or PIN code
 * @param country    country name (stored as free text, not ISO code)
 * @param isDefault  whether this is the user's default shipping address;
 *                   serialized as {@code "default"} in JSON output
 * @param createdAt  timestamp when this address was first created
 * @param updatedAt  timestamp of the most recent modification to this address
 * @author prabhatkrmishra
 * @since 1.0.0
 */
public record AddressResponse(

        /**
         * Unique identifier of the address.
         */
        Long id,

        /**
         * User-defined label for this address (e.g., "Home", "Office").
         */
        String label,

        /**
         * Recipient's full name.
         */
        String fullName,

        /**
         * Contact phone number.
         */
        String phone,

        /**
         * Primary address line.
         */
        String line1,

        /**
         * Secondary address line (optional).
         */
        String line2,

        /**
         * City name.
         */
        String city,

        /**
         * State or province.
         */
        String state,

        /**
         * Postal or ZIP code.
         */
        String postalCode,

        /**
         * Country name.
         */
        String country,

        /**
         * Whether this is the user's default address.
         */
        @JsonProperty("default")
        boolean isDefault,

        /**
         * Address creation timestamp.
         */
        Instant createdAt,

        /**
         * Address last update timestamp.
         */
        Instant updatedAt
) {

    /**
     * Constructs an {@link AddressResponse} from an {@link Address} entity.
     *
     * @param address source entity
     * @return response DTO
     */
    public static AddressResponse from(Address address) {
        return new AddressResponse(
                address.getId(),
                address.getLabel(),
                address.getFullName(),
                address.getPhone(),
                address.getLine1(),
                address.getLine2(),
                address.getCity(),
                address.getState(),
                address.getPostalCode(),
                address.getCountry(),
                address.isDefault(),
                address.getCreatedAt(),
                address.getUpdatedAt()
        );
    }
}
