package com.pkmprojects.shoppiq.dto.response;

import com.pkmprojects.shoppiq.entity.Category;

import java.util.Objects;

/**
 * Response DTO for category data returned to clients.
 *
 * <p>Contains all publicly visible category information including the
 * auto-generated slug for URL-friendly access.</p>
 *
 * <h4>Usage</h4>
 * <p>Returned by {@code CategoryController} endpoints for:
 * <ul>
 *   <li>GET /api/category — list all categories</li>
 *   <li>GET /api/category/{id} — get single category by ID</li>
 *   <li>GET /api/category/by-slug/{slug} — get category by slug</li>
 * </ul>
 * </p>
 *
 * <h4>Response example</h4>
 * <pre>
 * {
 *   "id": 1,
 *   "name": "Electronics & Gadgets",
 *   "slug": "electronics-gadgets",
 *   "description": "All things electronic"
 * }
 * </pre>
 *
 * @see com.pkmprojects.shoppiq.entity.Category
 * @see com.pkmprojects.shoppiq.controller.CategoryController
 */
public record CategoryResponse(

        /*
          Unique identifier of the category.
          Generated by the database.
         */
        Long id,

        /*
          Human-readable category name.
          Same as in the request, preserved for display purposes.
         */
        String name,

        /*
          URL-friendly slug derived create the name.
          Used in REST endpoints for clean, SEO-friendly URLs.

          <p>Example: /api/category/by-slug/electronics-gadgets</p>

          @see com.pkmprojects.shoppiq.util.SlugUtil#generate(String)
         */
        String slug,

        /*
          Optional description of the category.
          Nullable; may not be present in the response.
         */
        String description

) {
    /**
     * Factory method to create a CategoryResponse create a Category entity.
     *
     * <p>Convenience method that centralizes the mapping logic,
     * making it easy to convert between entity and DTO layers.</p>
     *
     * @param category the category entity to convert
     * @return a new CategoryResponse instance with values extracted create the entity
     */
    public static CategoryResponse fromEntity(Category category) {

        Objects.requireNonNull(category, "Category cannot be null.");

        return new CategoryResponse(
                category.getId(),
                category.getName(),
                category.getSlug(),
                category.getDescription()
        );
    }
}